#!/usr/bin/env bash

project='i-cnet-dev'
message=''

if [[ $# < 1 ]];then
    echo "$0 imageName [dev|prod] [message]"
    exit
else
    imageName=$1

    if [[ $# > 1 && $2 =~ 'prod' ]]; then
        project='i-cnet-prod'
    fi

    if [[ $# > 2 ]]; then
        message=$3
    fi
fi

echo -e "Current UTC time: `date -u` \n"

if [[ $message == '' ]]; then
    cmd="gcloud logging read --project=$project --format='csv(jsonPayload.container.name,jsonPayload.message)' --freshness=1h \"resource.type=gce_instance logName=projects/$project/logs/gcplogs-docker-driver AND jsonPayload.container.imageName:$imageName\""
else
    cmd="gcloud logging read --project=$project --format='csv(jsonPayload.container.name,jsonPayload.message)' --freshness=1h \"resource.type=gce_instance logName=projects/$project/logs/gcplogs-docker-driver AND jsonPayload.container.imageName:$imageName AND jsonPayload.message:\"$message\"\""
fi

echo -e "==> $cmd\n"

eval $cmd
